### PR TITLE
Concept cleanup

### PR DESCRIPTION
**Pull request by philbarker**
Adds latest greatest predicate definition file.
Moves "canonical" term definition files into a single folder.
Moves example/testing files into single folder.

### CODE REVIEW

**Comment by philbarker** [comment]
So many Fs in Tests/test, I guess I moved something that is used in the tests?

**Comment by shlag3n** [comment]
> So many Fs in Tests/test, I guess I moved something that is used in the tests?

@philbarker yes, it's about `concepts/desmAbstractClasses.json`, i can update the tests and merge PR after checks will be passed.

**Comment by philbarker** [comment]
Thank you @shlag3n, no hurry, make sure it doesn't disrupt more important work.

**Comment by shlag3n** [comment]
@philbarker tests were fixed, changes are merged to the main branch.

**Pull request merged**
