### PR TITLE
(#376) updated mapping predicate select/commenting

### PR DESCRIPTION
**Pull request by shlag3n**
#376

### CODE REVIEW

**Review by excelsior — CHANGES_REQUESTED** [review]
Works as expected, but there is a minor UI issue if the user is impersonated by an admin. The modal overlaps with the sticky header above:

Screenshot 2024-06-12 at 16 07 18

How about positioning the modal in the center of the screen?

**Comment by edgarf** [comment]
@philbarker should we center the modal, or make it be "over" the sticky bar?

**Comment by excelsior** [comment]
Some of those modals are so large that centering them will have no effect. How about increasing the top margit a notch for now?

**Comment by philbarker** [comment]
@edgarf I'm happy with what @excelsior suggests, positioning them just below the "impersonating" banner would make sense

**Pull request merged**
